"""
Django settings for snowAIv2 project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-754g_4e%89qf6mj(&0q3oyk(6fz54h70*+@$jfr635n8$esjpn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "http://localhost:5173",
    "backend-production-c0ab.up.railway.app",
    "https://silencium-ascendio.vercel.app",
    "https://crystal-mindforge.vercel.app",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ]
}


# CORS_ALLOW_CREDENTIALS = True

CORS_ORIGIN_WHITELIST = (
    'http://localhost:5173',
    'https://silencium-ascendio.vercel.app',
    "https://crystal-mindforge.vercel.app",
    "http://zinaida-production.up.railway.app"
)


CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'https://backend-production-c0ab.up.railway.app',
    'https://silencium-ascendio.vercel.app',
    'https://crystal-mindforge.vercel.app',
    'http://zinaida-production.up.railway.app'
    # 'https://www.metatrader5.com/en/trading-platform/web-trading',
]

AUTH_USER_MODEL = 'snowAIWeb.User'

# Application definition

AUTHENTICATION_BACKENDS = [
    'snowAIWeb.backends.EmailBackend',
]

SESSION_ENGINE = "django.contrib.sessions.backends.db"

INSTALLED_APPS = [
    # 'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'snowAIWeb',
]

MIDDLEWARE = [
    'django.middleware.csrf.CsrfViewMiddleware',
    'snowAIv2.middleware.CustomCorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'snowAIv2.middleware.UserEmailMiddleware',
]

ROOT_URLCONF = 'snowAIv2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
# SESSION_COOKIE_NAME = "my_session_name"


WSGI_APPLICATION = 'snowAIv2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres', 
        'PASSWORD': 'FgegFFfbD1F6ECGG13Ff5bA1B1GFD2dB',
        'HOST': 'monorail.proxy.rlwy.net',
        'PORT': '19124',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF_TRUSTED_ORIGINS = [
#     'https://frontend-2yg4.vercel.app/',
#     'http://localhost:5173/',
# ]

# CORS_ALLOW_ALL_ORIGINS = True # If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
# CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://snowai.vercel.app",
    "http://localhost:5173",
    'https://silencium-ascendio.vercel.app',
    'https://crystal-mindforge.vercel.app',
    'http://zinaida-production.up.railway.app',
    # "https://www.metatrader5.com/en/trading-platform/web-trading",
] # If this is used, then not need to use `CORS_ALLOW_ALL_ORIGINS = True`


# settings.py
# Adjust the worker timeout value as per your requirements, e.g., 60 seconds
# WORKER_TIMEOUT = 600
