from django.urls import path
from .views import *
from . import views
 
urlpatterns = [
    # ... other URL patterns
    path('register/', UserRegistrationView.as_view(), name='user-registration'),
    path('check_email/', views.check_email, name='check_email'),
    path('tell_us_more/create/', views.TellUsMoreCreateView.as_view(), name='tell_us_more_create'),
    path('login/', UserLoginView.as_view(), name='user-login'),
    path('new_trade/', TradeView.as_view(), name='new_trade'),
    path('all_trades/<str:email>/', views.all_trades, name='all_trades'),
    path('full_trade/<int:trade_id>/', views.full_trade, name='full_trade'),
    path('user_overview/<str:user_email>/', views.user_overview, name='overview'),
    path('save_journal/<str:user_email>/', views.save_journal, name='save_journal'),
    path('all_journals/<str:user_email>/', views.fetch_journals, name='all_journals'),
    path('view_journal/<int:journal_id>/', views.view_journal, name='view_journal'),
    path('upcoming_news/<str:user_email>/', views.upcoming_news, name='upcoming_news'),
    path('get_user_data/<str:user_email>/', views.get_user_data, name='user_data'),
    path('save_conversation/<str:user_email>/<str:identifier>/', views.save_conversation, name='save_conversation'),
    path('fetch_conversations/<str:user_email>/', views.fetch_conversations, name='fetch_conversations'),
    path('fetch_conversation/<str:conversation_id>/', views.fetch_conversation, name='fetch_conversation'),
    path('update_conversation/<str:conversation_id>/', views.update_conversation, name='update_conversation'),
    path('delete_conversation/<str:conversation_id>/', views.delete_conversation, name='delete_conversation'),
    path('get_openai_key', views.get_openai_key, name='get_openai_key'),
    path('update_user_data/<str:user_email>/', views.update_tell_us_more, name='update_user_data'),
    path('update_assets/<str:user_email>/', views.update_user_assets, name='update_assets'),
    path('fetch_user_news_data/<str:user_email>', views.fetch_user_news_data, name='fetch_news_data'),
    # path('save_news_data', views.save_news_data, name='save_news_data'),
    path('create-bot/<str:type_1>/<str:type_2>/<int:ma1>/<int:ma2>/<str:dataframe>/<str:backtest_period>', views.moving_average_bot, name='create-bot'),
    path('create-bot/bbands/<int:length>/<int:std>/<str:dataframe>/<str:backtest_period>', views.bbands_bot, name='create-bot-bbands'),
    path('create-bot/rsi/<str:length>/<str:overbought_level>/<str:oversold_level>/<str:dataframe>/<str:backtest_period>', views.rsi_bot, name='create-bot-rsi'),
    path('create-bot/momentum/<str:dataframe>/<str:backtest_period>', views.momentum_bot, name='create-bot-momentum'),
    path('create-bot/candlesticks/<str:dataframe>/<str:backtest_period>', views.candlesticks_bot, name='create-bot-candlesticks'),
    path('api-call/<str:asset>', views.api_call, name='api-call'),
    path('api-test', views.api_test, name='api-test'),
    path('new-test', views.new_test, name='new-test'),
    path('download-mq4/<str:bot>', views.download_mq4_file, name='download_mq4_file'),
    path('process-image', views.process_image, name='process_image'),
    path('chosen-models/<str:user_email>/<int:magic_number>', views.chosen_models, name='chosen_models'),
    path('run-bot/<str:user_email>/<int:magic_number>/<str:asset>', views.run_bot, name='run-bot'),
    path('run-backtest/<str:dataframe>/<str:backtest_period>', views.run_backtest, name='run-backtest'),
    path('update-news-data/<str:user_email>', views.update_news_data, name='update-news-data'),
    path('interest-rates-data', views.interest_rates, name='interest-rates-data'),
    path('genesys', views.genesys, name='genesys'),
    path('save-dataset/<str:dataset>', views.save_dataset, name='save-dataset'),
    path('split-dataset', views.split_dataset, name='split-dataset'),
    path('set-init-capital', views.set_init_capital, name='set-init-capital'),
    path('genesys-live/<int:identifier>/<int:num_positions>/<str:asset>/<str:interval>/<str:order_ticket>/<str:bot_id>', views.genesys_live, name='genesys-live'),
    path('save-genesys-model', views.save_genesys_model, name='save-genesys-model'),
    path('test-cnn/<str:asset>/<str:interval>/<int:num_days>', views.test_cnn, name='test-cnn'),
    path('save-new-trade-model/<int:model_id>/<int:initial_equity>/<str:order_ticket>/<str:asset>/<str:volume>/<str:type_of_trade>/<str:timeframe>/<str:bot_id>', views.save_new_trade_model, name='save-new-trade-model'),
    path('update-trade-model/<int:model_id>/<str:order_ticket>/<str:profit>', views.update_trade_model, name='update-trade-model'),
    path('get-model-performance', views.get_model_performance, name='get-model-performance'),
    path('delete-bot/<str:bot_id>', views.delete_unique_bot, name='delete-bot'),
    path('clear-bots', views.clear_stuff, name='clear-bots'),
    path('test-date/<str:asset>', views.test_date, name='test-date'),
    path('daily-brief', views.daily_brief, name='daily-brief'),
    path('fetch-daily-brief-data', views.fetch_daily_brief_data, name='fetch-daily-brief-data'),
    path('get-user-assets', views.get_user_assets, name='get-user-assets'),
    path('fetch-asset-data/<str:asset>', views.fetch_asset_data, name='fetch-asset-data'),
    path('fetch-asset-data-from-models/<str:asset>', views.fetch_asset_data_from_models, name='fetch-asset-data-from-models'),
    path('get-asset-summary/<str:asset>', views.get_asset_summary, name='get-asset-summary'),
    path('reflections-summary/<str:asset>', views.reflections_summary, name='reflections-summary'),
    path('generate-cot-data', views.generate_cot_data, name='generate-cot-data'),
    path('create-chill-data', views.create_chill_data, name='create-chill-data'),
    path('fetch-chill-sections', views.fetch_chill_sections, name='fetch-chill-sections'),
    path('fetch-chill-data', views.fetch_chill_data, name='fetch-chill-data'), 
    path('edit-chill-data', views.edit_chill_data, name='edit-chill-data'),
    path('delete-chill-entry', views.delete_chill_entry, name='delete-chill-entry'),
    path('fetch-trading-images', views.fetch_trading_images, name='fetch-trading-images'),
    path('alert-bot', views.alert_bot, name='alert-bot'),
    path('create-finetuning-data', views.create_finetuning_data, name='create-finetuning-data'),
    path('create-combined-finetuning-data', views.create_combined_finetuning_data, name='create-combined-finetuning-data'),
    path('create-image-finetuning-data', views.create_image_finetuning_data, name='create-image-finetuning-data'),
    path('accounts/', views.get_accounts, name='get_accounts'),
    path('create_account/', views.create_account, name='create_account'),
    path('delete_account/<int:account_id>/', views.delete_account, name='delete_account'),
    path('accounts/update/', views.update_account, name='update_account'),
    path('get-trading-analytics', views.get_trading_analytics, name='get-trading-analytics'),
    path('create-new-trade-data', views.create_new_trade_data, name='create-new-trade-data'),
    path('fetch-trading-data', views.fetch_trading_data, name='fetch-trading-data'),
    path('fetch-account-data/', views.fetch_account_data, name='fetch-account-data'),
    path('set-daily-brief-assets', views.set_daily_brief_assets, name='set-daily-brief-assets'),
    path('time-trading-analytics', views.time_trading_analytics, name='trading_analytics'),
    # path('api/trader-analysis/', views.trader_analysis, name='trader-analysis'),
    path('api/trader-analysis/', views.get_trader_analysis, name='trader-analysis'),
    path('save-backtest-model-data', views.save_backtest_model_data, name='save-backtest-model-data'),
    path('trigger-backtest', views.trigger_backtest, name='trigger-backtest'),
    path('fetch-backtested-results', views.fetch_backtested_results, name='fetch-backtested-results'),
    path('delete-backtest-model', views.delete_backtest_model, name='delete-backtest-model'),
    path('generate-idea', views.generate_idea, name='generate-idea'),
    path('fetch-ideas', views.fetch_ideas, name='fetch-ideas'),
    path('delete-idea', views.delete_idea, name='delete-idea'),
    path('update-idea-tracker', views.update_idea_tracker, name='update-idea-tracker'),
    path('update-idea', views.update_idea, name='update-idea'),
    path('ai-account-summary', views.get_ai_account_summary, name='ai-account-summary'),
    path('save-quiz', views.save_quiz, name='save-quiz'),
    path('fetch-saved-quizzes', views.fetch_saved_quizzes, name='fetch-saved-quizzes'),
    path('delete-quiz/<int:quiz_id>', views.delete_quiz, name='delete-quiz'),
    path('save-music', views.save_music, name='save-music'),
    path('fetch-music', views.fetch_music, name='fetch-music'),
    path('stream-music/<int:song_id>', views.stream_music, name='stream_music'),
    path('delete-music', views.delete_music, name='delete-music'),
    path('fetch-asset-update/', views.fetch_asset_update, name='fetch-asset-update'),
    path('get-tracked-assets/', views.get_tracked_assets, name='get-tracked-assets'),
    path('add-tracked-asset/', views.add_tracked_asset, name='add-tracked-asset'),
    path('remove-tracked-asset/', views.remove_tracked_asset, name='remove-tracked-asset'),
    path('api/trade-ideas/', views.get_trade_ideas, name='get_trade_ideas'),
    path('api/trade-ideas/create/', views.create_trade_idea, name='create_trade_idea'),
    path('api/trade-ideas/update/<int:id>/', views.update_trade_idea, name='update_trade_idea'),
    path('api/trade-ideas/delete/<int:id>/', views.delete_trade_idea, name='delete_trade_idea'),
    path('api/prop-firms/', views.prop_firm_list, name='prop_firm_list'),
    path('api/prop-firms/<int:firm_id>/', views.prop_firm_detail, name='prop_firm_detail'),
    path('api/prop-metrics/', views.metrics_list, name='metrics_list'),
    path('api/prop-metrics/<int:metric_id>/', views.metric_detail, name='metric_detail'),
    path('api/economic-events/', views.economic_events_list, name='economic-events-list'),
    path('api/economic-events/<int:pk>/', views.economic_event_detail, name='economic-event-detail'),
    path('api/data-calendar-economic-events/', views.data_calendar_economic_events_list, name='economic-events-list'),
    path('api/data-calendar-economic-events/<int:event_id>/', views.data_calendar_economic_event_detail, name='economic-event-detail'),
    path('api/unique-economic-events/', views.unique_economic_events_list, name='unique_economic_events_list'),
    path('api/event-history/<str:event_name>/', views.event_history, name='event-history'),
    path('api/cot/', views.generate_econ_cot_data, name='generate_econ_cot_data'),
    path('api/generate_econ_ai_summary/', views.generate_econ_ai_summary, name='generate_econ_ai_summary'),
    # path('save_forex_factory_news', views.save_forex_factory_news, name='save_forex_factory_news'),
    # path('get_forex_factory_events', views.get_forex_factory_events, name='get_forex_factory_events'),
    path('save_forex_factory_news', views.save_forex_factory_news, name='save_forex_factory_news'),
    path('fetch_news_data_api', views.fetch_news_data_api, name='fetch_news_data_api'),
    # Get all trades for a specific account
    path('api/trades-calendar/', views.get_trades_by_account_calendar, name='get_trades_by_account'),
    # Get trades within a date range
    path('api/trades/date-range/', views.get_trades_by_date_range_calendar, name='get_trades_by_date_range'),
    # Get trade summary statistics
    path('api/trades/summary-calendar/', views.get_trade_summary_calendar, name='get_trade_summary'),
    # Create a new trade
    path('api/trades/create-calendar/', views.create_trade_calendar, name='create_trade'),


    # create appproprate urls.py here
    # path('test-async-backtest', views.test_async_backtest, name='test-async-backtest'),
    

    path('zinaida-feedback', views.zinaida_feedback_form, name='zinaida-feedback'),


    path('contact-us', views.contact_us, name='contact-us'),
    path('book-order', views.book_order, name='book-order'),
    path('api/register/', UserRegistrationView.as_view(), name='user-register'),
    path('api/login/', views.user_login, name='user-login'),
    path('api/csrf_token/', views.get_csrf_token, name='get_csrf_token'),
    # path('fetch_user_email', views.fetch_user_email, name='fetch_user_email')
]


