# Generated by Django 4.2.4 on 2023-09-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowAIWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='tags',
            field=models.CharField(default='', max_length=300),
        ),
    ]
