# Generated by Django 4.2.4 on 2023-09-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowAIWeb', '0002_journals_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=30000)),
                ('day_created', models.DateTimeField()),
            ],
        ),
    ]
