# Generated by Django 4.2.4 on 2023-09-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowAIWeb', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.TextField(),
        ),
    ]
