# Generated by Django 4.2.4 on 2023-11-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowAIWeb', '0004_alter_news_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_type', models.CharField(max_length=200)),
                ('params', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovingAverageBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma1_type', models.CharField(max_length=20)),
                ('ma2_type', models.CharField(max_length=20)),
                ('ma1', models.IntegerField()),
                ('ma2', models.IntegerField()),
            ],
        ),
    ]
