# Generated by Django 4.2.4 on 2023-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowAIWeb', '0005_createmodel_movingaveragebot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254)),
                ('magic_number', models.IntegerField()),
                ('time_saved', models.DateTimeField()),
                ('parameters', models.TextField()),
            ],
        ),
    ]
