# Generated by Django 4.2.4 on 2024-01-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("snowAIWeb", "0006_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="user_email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
