# Generated by Django 4.2.4 on 2024-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0008_alter_news_symbol"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset", models.CharField(max_length=30)),
            ],
        ),
    ]
