# Generated by Django 4.2.4 on 2024-04-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0011_bookorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="interested_product",
            field=models.TextField(),
        ),
    ]
