# Generated by Django 4.2.4 on 2024-04-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0013_bookorder_number_of_units_bookorder_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="number_of_units",
            field=models.CharField(default=""),
        ),
    ]
