# Generated by Django 4.2.4 on 2024-04-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0014_alter_bookorder_number_of_units"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="phone_number",
            field=models.IntegerField(),
        ),
    ]
