# Generated by Django 4.2.4 on 2024-04-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0015_alter_bookorder_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookorder",
            name="number_of_units",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="bookorder",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
