# Generated by Django 4.2.4 on 2024-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0017_customuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="SplitDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_year", models.CharField(max_length=30)),
                ("end_year", models.CharField(max_length=30)),
            ],
        ),
    ]
