# Generated by Django 4.2.4 on 2024-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0018_splitdataset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetInitCapital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("initial_capital", models.FloatField()),
            ],
        ),
    ]
