# Generated by Django 4.2.4 on 2024-04-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0019_setinitcapital"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenesysLive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.CharField(max_length=100)),
                ("model_code", models.TextField()),
                ("current_equity", models.FloatField()),
                ("take_profit_number", models.FloatField()),
                ("take_profit_type", models.CharField(max_length=20)),
                ("stop_loss_number", models.FloatField()),
                ("stop_loss_type", models.CharField(max_length=20)),
                ("true_initial_equity", models.FloatField()),
            ],
        ),
    ]
