# Generated by Django 4.2.4 on 2024-05-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0020_genesyslive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genesyslive",
            name="model_id",
            field=models.IntegerField(),
        ),
    ]
