# Generated by Django 4.2.4 on 2024-05-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0021_alter_genesyslive_model_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genesyslive",
            name="current_equity",
        ),
        migrations.RemoveField(
            model_name="genesyslive",
            name="stop_loss_number",
        ),
        migrations.RemoveField(
            model_name="genesyslive",
            name="stop_loss_type",
        ),
        migrations.RemoveField(
            model_name="genesyslive",
            name="take_profit_number",
        ),
        migrations.RemoveField(
            model_name="genesyslive",
            name="take_profit_type",
        ),
    ]
