# Generated by Django 4.2.4 on 2024-05-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0022_remove_genesyslive_current_equity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genesyslive",
            name="model_id",
            field=models.IntegerField(unique=True),
        ),
    ]
