# Generated by Django 4.2.4 on 2024-06-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0023_alter_genesyslive_model_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="tradeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_id", models.IntegerField()),
                ("model_code", models.TextField()),
                ("initial_equity", models.FloatField()),
                ("order_ticket", models.IntegerField()),
                ("asset", models.CharField(max_length=20)),
                ("profit", models.FloatField()),
                ("volume", models.FloatField()),
                ("type_of_trade", models.CharField(max_length=10)),
            ],
        ),
    ]
