# Generated by Django 4.2.4 on 2024-06-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0024_trademodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademodel",
            name="timeframe",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="trademodel",
            name="asset",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="trademodel",
            name="profit",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="trademodel",
            name="type_of_trade",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="trademodel",
            name="volume",
            field=models.FloatField(null=True),
        ),
    ]
