# Generated by Django 4.2.4 on 2024-06-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0025_trademodel_timeframe_alter_trademodel_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trademodel",
            name="order_ticket",
            field=models.TextField(),
        ),
    ]
