# Generated by Django 4.2.4 on 2024-07-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0027_uniquebot"),
    ]

    operations = [
        migrations.AddField(
            model_name="trademodel",
            name="date_taken",
            field=models.DateTimeField(null=True),
        ),
    ]
