# Generated by Django 4.2.4 on 2024-07-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0028_trademodel_date_taken"),
    ]

    operations = [
        migrations.CreateModel(
            name="dailyBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.TextField()),
                ("summary", models.TextField()),
                ("last_update", models.DateTimeField(null=True)),
            ],
        ),
    ]
