# Generated by Django 4.2.4 on 2024-10-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0029_dailybrief"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.TextField()),
                ("text", models.TextField()),
            ],
        ),
    ]
