# Generated by Django 4.2.4 on 2024-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0030_chill"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=50)),
                ("price", models.FloatField()),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("<", "Less than"),
                            (">", "Greater than"),
                            ("=", "Equal to"),
                        ],
                        max_length=1,
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
            },
        ),
    ]
