# Generated by Django 4.2.4 on 2025-01-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0032_account_accounttrades"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBriefAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=50)),
            ],
        ),
    ]
