# Generated by Django 4.2.4 on 2025-02-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0034_feedbackform"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttrades",
            name="date_entered",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
