# Generated by Django 4.2.4 on 2025-02-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0035_accounttrades_date_entered"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestModels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chosen_dataset",
                    models.CharField(
                        help_text="Name or path of the dataset used.", max_length=255
                    ),
                ),
                (
                    "generated_code",
                    models.TextField(help_text="Generated code for the backtest."),
                ),
                (
                    "model_backtested",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the model was backtested.",
                    ),
                ),
                (
                    "dataset_start",
                    models.CharField(
                        help_text="Start date of the dataset (YYYY-MM-DD format).",
                        max_length=50,
                    ),
                ),
                (
                    "dataset_end",
                    models.CharField(
                        help_text="End date of the dataset (YYYY-MM-DD format).",
                        max_length=50,
                    ),
                ),
                (
                    "initial_capital",
                    models.FloatField(help_text="Initial capital for the backtest."),
                ),
            ],
        ),
    ]
