# Generated by Django 4.2.4 on 2025-02-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0037_backtestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="backtestresult",
            name="backtest_model",
            field=models.ForeignKey(
                help_text="Related backtest model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="snowAIWeb.backtestmodels",
            ),
        ),
    ]
