# Generated by Django 4.2.4 on 2025-03-04 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0039_ideamodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quiz_name", models.CharField(max_length=255)),
                ("total_questions", models.IntegerField()),
                ("correct_answers", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SavedQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("selected_answer", models.CharField(max_length=255)),
                ("correct_answer", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField()),
                (
                    "saved_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="snowAIWeb.savedquiz",
                    ),
                ),
            ],
        ),
    ]
