# Generated by Django 4.2.4 on 2025-03-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0040_savedquiz_savedquizquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
