# Generated by Django 4.2.4 on 2025-03-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0041_musicmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musicmodel",
            name="file",
            field=models.FileField(upload_to="music/"),
        ),
    ]
