# Generated by Django 4.2.4 on 2025-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0042_alter_musicmodel_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetsTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=50)),
            ],
        ),
    ]
