# Generated by Django 4.2.4 on 2025-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0044_tradeidea"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tradeidea",
            options={},
        ),
        migrations.AddField(
            model_name="tradeidea",
            name="entry_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradeidea",
            name="stop_loss",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tradeidea",
            name="target_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tradeidea",
            name="trade_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("executed", "Executed"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
