# Generated by Django 4.2.4 on 2025-04-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0045_alter_tradeidea_options_tradeidea_entry_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeidea",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("win", "Win"),
                    ("loss", "Loss"),
                    ("breakeven", "Breakeven"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
