# Generated by Django 4.2.4 on 2025-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0046_tradeidea_outcome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="musicmodel",
            name="file",
        ),
        migrations.AddField(
            model_name="musicmodel",
            name="content_type",
            field=models.CharField(default="audio/mpeg", max_length=100),
        ),
        migrations.AddField(
            model_name="musicmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="musicmodel",
            name="file_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="musicmodel",
            name="file_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="musicmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
