# Generated by Django 4.2.4 on 2025-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0047_remove_musicmodel_file_musicmodel_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tellusmore",
            name="benefits",
            field=models.CharField(max_length=1001),
        ),
    ]
