# Generated by Django 4.2.4 on 2025-04-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0048_alter_tellusmore_benefits"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_accounts", models.IntegerField(default=0)),
                (
                    "total_capital_managed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_risk_reward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("avg_session_time", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropFirm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="prop_firm_logos/"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PropFirmAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=100)),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CHALLENGE", "Challenge"),
                            ("VERIFICATION", "Verification"),
                            ("FUNDED", "Funded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("LIVE", "Live"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "current_equity",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "daily_loss_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_loss_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "profit_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prop_firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="snowAIWeb.propfirm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TradingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "starting_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "ending_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=15)),
                ("session_time_minutes", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "voice_memo",
                    models.FileField(blank=True, null=True, upload_to="voice_memos/"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_days",
                        to="snowAIWeb.propfirmaccount",
                    ),
                ),
            ],
            options={
                "unique_together": {("account", "date")},
            },
        ),
        migrations.CreateModel(
            name="PropTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=50)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=15)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=15, null=True
                    ),
                ),
                ("size", models.DecimalField(decimal_places=5, max_digits=15)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "pnl",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("strategy", models.CharField(blank=True, max_length=100, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="snowAIWeb.propfirmaccount",
                    ),
                ),
                (
                    "trading_day",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="snowAIWeb.tradingday",
                    ),
                ),
            ],
        ),
    ]
