# Generated by Django 4.2.4 on 2025-04-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0049_managementmetrics_propfirm_propfirmaccount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propfirm",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="propfirm",
            name="description",
        ),
        migrations.RemoveField(
            model_name="propfirm",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="propfirm",
            name="logo",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="propfirmaccount",
            name="prop_firm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="firm_accounts",
                to="snowAIWeb.propfirm",
            ),
        ),
        migrations.CreateModel(
            name="PropFirmManagementMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("challenge", "Challenge"),
                            ("verification", "Verification"),
                            ("funded", "Funded"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("live", "Live"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "starting_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "current_equity",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "profit_target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "max_drawdown",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("start_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "prop_firm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="snowAIWeb.propfirm",
                    ),
                ),
            ],
        ),
    ]
