# Generated by Django 4.2.4 on 2025-06-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0051_economicevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperGPT",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("file_name", models.CharField(max_length=255)),
                ("file_data", models.TextField()),
                ("file_size", models.BigIntegerField()),
                ("extracted_text", models.TextField()),
                ("ai_summary", models.TextField()),
                ("personal_notes", models.TextField(blank=True)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
    ]
