# Generated by Django 4.2.4 on 2025-07-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0052_papergpt"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraderGPTForexAnalysisSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("user_email", models.EmailField(max_length=254)),
                ("currency_pairs", models.JSONField()),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TraderGPTForexAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_pair", models.CharField(max_length=10)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confidence_score", models.IntegerField()),
                ("entry_strategy", models.TextField()),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time_horizon", models.CharField(max_length=50)),
                ("target_price", models.CharField(max_length=20)),
                ("stop_loss", models.CharField(blank=True, max_length=20, null=True)),
                ("key_factors", models.TextField()),
                ("technical_analysis", models.TextField(blank=True, null=True)),
                ("fundamental_analysis", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="snowAIWeb.tradergptforexanalysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TraderGPTAnalysisNewsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("highlights", models.TextField(blank=True, null=True)),
                ("relevance_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_news",
                        to="snowAIWeb.tradergptforexanalysisresult",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TraderGPTAnalysisEconomicEventLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relevance_score", models.IntegerField(default=0)),
                ("impact_assessment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_economic_events",
                        to="snowAIWeb.tradergptforexanalysisresult",
                    ),
                ),
                (
                    "economic_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="snowAIWeb.economicevent",
                    ),
                ),
            ],
        ),
    ]
