# Generated by Django 4.2.4 on 2025-07-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0054_analysisexecutionlog_watchedtradingasset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradergptanalysisrecord",
            name="resistance_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tradergptanalysisrecord",
            name="stop_loss_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tradergptanalysisrecord",
            name="support_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tradergptanalysisrecord",
            name="take_profit_level",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
