# Generated by Django 4.2.4 on 2025-07-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0055_alter_tradergptanalysisrecord_resistance_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITradingCouncilConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(max_length=100, unique=True)),
                (
                    "title",
                    models.CharField(
                        default="AI Trading Council Discussion", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("participating_assets", models.JSONField(default=list)),
                ("total_participants", models.IntegerField(default=0)),
                ("conversation_data", models.JSONField(default=dict)),
                ("conversation_summary", models.TextField(blank=True)),
                (
                    "overall_economic_outlook",
                    models.CharField(
                        choices=[
                            ("very_positive", "Very Positive"),
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                            ("very_negative", "Very Negative"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "global_market_sentiment",
                    models.CharField(default="neutral", max_length=20),
                ),
                (
                    "market_volatility_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("extreme", "Extreme"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("major_economic_themes", models.JSONField(default=list)),
                ("currency_strength_rankings", models.JSONField(default=dict)),
                ("risk_factors_identified", models.JSONField(default=list)),
                ("opportunity_areas", models.JSONField(default=list)),
                ("bullish_sentiment_count", models.IntegerField(default=0)),
                ("bearish_sentiment_count", models.IntegerField(default=0)),
                ("neutral_sentiment_count", models.IntegerField(default=0)),
                ("average_confidence_score", models.FloatField(default=0.0)),
                ("execution_time_seconds", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "ai_trading_council_conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITradingCouncilParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_code", models.CharField(max_length=10)),
                ("participant_name", models.CharField(max_length=100)),
                (
                    "market_sentiment",
                    models.CharField(default="neutral", max_length=20),
                ),
                ("confidence_score", models.IntegerField(default=50)),
                ("risk_assessment", models.CharField(default="medium", max_length=20)),
                ("key_insights", models.JSONField(default=list)),
                ("turns_spoken", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="snowAIWeb.aitradingcouncilconversation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_trading_council_participants",
                "unique_together": {("conversation", "asset_code")},
            },
        ),
    ]
