# Generated by Django 4.2.4 on 2025-07-31 13:59

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0056_aitradingcouncilconversation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmCompliance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "firm_name",
                    models.CharField(max_length=200, verbose_name="Firm Name"),
                ),
                (
                    "firm_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="firm_logos/",
                        verbose_name="Firm Logo",
                    ),
                ),
                (
                    "personal_notes",
                    models.TextField(
                        help_text="Your personal compliance notes and rules",
                        verbose_name="Personal Notes",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Firm Compliance",
                "verbose_name_plural": "Firm Compliance Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
