# Generated by Django 4.2.4 on 2025-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0057_firmcompliance"),
    ]

    operations = [
        migrations.AddField(
            model_name="papergpt",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
