# Generated by Django 4.2.4 on 2025-09-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0059_snowaimlmodellogentry_snowaimodeldatasetfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FingerprintStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        default="tlotlo.motingwe@example.com",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("is_registered", models.BooleanField(default=False)),
                ("domain", models.CharField(blank=True, max_length=255, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
