# Generated by Django 4.2.4 on 2025-09-23 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0061_snowaibacktestinggptsummary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTDiscussion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discussion_id",
                    models.CharField(
                        default="current_discussion", max_length=100, unique=True
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("total_messages", models.IntegerField(default=0)),
                ("central_gpt_summary", models.TextField(blank=True)),
                ("discussion_metrics", models.JSONField(default=dict)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("manual", "Manual")],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="GPTDiscussionMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gpt_system",
                    models.CharField(
                        choices=[
                            ("TraderHistoryGPT", "TraderHistoryGPT"),
                            ("MacroGPT", "MacroGPT"),
                            ("IdeaGPT", "IdeaGPT"),
                            ("BacktestingGPT", "BacktestingGPT"),
                            ("PaperGPT", "PaperGPT"),
                            ("ResearchGPT", "ResearchGPT"),
                            ("CentralGPT", "CentralGPT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("turn_number", models.IntegerField(default=1)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="snowAIWeb.gptdiscussion",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
