# Generated by Django 4.2.4 on 2025-09-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0063_snowaitranscriptsearchhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAITranscriptAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_uuid",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("executive_summary", models.TextField()),
                ("key_themes", models.JSONField(default=list)),
                ("economic_opportunities", models.JSONField(default=list)),
                ("economic_risks", models.JSONField(default=list)),
                ("policy_implications", models.JSONField(default=list)),
                ("overall_sentiment", models.CharField(max_length=20)),
                ("sentiment_confidence", models.FloatField(default=0.0)),
                ("market_outlook", models.CharField(max_length=20)),
                ("inflation_mentions", models.JSONField(default=dict)),
                ("interest_rate_mentions", models.JSONField(default=dict)),
                ("gdp_mentions", models.JSONField(default=dict)),
                ("unemployment_mentions", models.JSONField(default=dict)),
                ("policy_actions_suggested", models.JSONField(default=list)),
                ("market_predictions", models.JSONField(default=list)),
                (
                    "analysis_model_used",
                    models.CharField(default="gpt-4o-mini", max_length=50),
                ),
                (
                    "analysis_prompt_version",
                    models.CharField(default="v1.0", max_length=20),
                ),
                ("analysis_duration_seconds", models.FloatField(blank=True, null=True)),
                ("analysis_word_count", models.IntegerField(default=0)),
                ("analysis_created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis_updated_at", models.DateTimeField(auto_now=True)),
                ("analysis_completeness_score", models.FloatField(default=0.0)),
                ("key_insights_count", models.IntegerField(default=0)),
                (
                    "transcript",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis",
                        to="snowAIWeb.snowaivideotranscriptrecord",
                    ),
                ),
            ],
            options={
                "db_table": "snowai_transcript_analysis",
                "ordering": ["-analysis_created_at"],
                "indexes": [
                    models.Index(
                        fields=["overall_sentiment"],
                        name="snowai_tran_overall_15fe71_idx",
                    ),
                    models.Index(
                        fields=["market_outlook"], name="snowai_tran_market__40c49a_idx"
                    ),
                    models.Index(
                        fields=["analysis_created_at"],
                        name="snowai_tran_analysi_f50337_idx",
                    ),
                ],
            },
        ),
    ]
