# Generated by Django 4.2.4 on 2025-10-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0064_snowaitranscriptanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIHedgeFundEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for logo (e.g., imgur, cloudinary)",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                (
                    "aum",
                    models.CharField(
                        blank=True,
                        help_text="Assets Under Management",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("strategy", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "headquarters",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("website", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SnowAI Hedge Fund Entity",
                "verbose_name_plural": "SnowAI Hedge Fund Entities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIHedgeFundResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("interview", "Interview"),
                            ("video", "Video"),
                            ("report", "Report"),
                            ("other", "Other"),
                        ],
                        default="article",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hedge_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="snowAIWeb.snowaihedgefundentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Hedge Fund Resource",
                "verbose_name_plural": "SnowAI Hedge Fund Resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIHedgeFundKeyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "wikipedia_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL for photo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "hedge_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_people",
                        to="snowAIWeb.snowaihedgefundentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Hedge Fund Key Person",
                "verbose_name_plural": "SnowAI Hedge Fund Key People",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIHedgeFundPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "return_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual return percentage",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "hedge_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_data",
                        to="snowAIWeb.snowaihedgefundentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Hedge Fund Performance",
                "verbose_name_plural": "SnowAI Hedge Fund Performance Data",
                "ordering": ["year"],
                "unique_together": {("hedge_fund", "year")},
            },
        ),
    ]
