# Generated by Django 4.2.4 on 2025-11-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0065_snowaihedgefundentity_snowaihedgefundresource_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetBiasRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "bias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Asset Bias Recommendation",
                "verbose_name_plural": "Asset Bias Recommendations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
