# Generated by Django 4.2.4 on 2025-11-16 07:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0066_assetbiasrecommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIVideoCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "SnowAI Video Category",
                "verbose_name_plural": "SnowAI Video Categories",
                "db_table": "snowai_video_categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIVideoEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_title", models.CharField(max_length=255)),
                ("video_url", models.URLField(max_length=500)),
                (
                    "date_entered",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snowai_videos",
                        to="snowAIWeb.snowaivideocategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Video Entry",
                "verbose_name_plural": "SnowAI Video Entries",
                "db_table": "snowai_video_entries",
                "ordering": ["-date_entered"],
            },
        ),
    ]
