# Generated by Django 4.2.4 on 2025-12-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0067_snowaivideocategory_snowaivideoentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAITradingWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snow_agent_name",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("snow_weights_data", models.JSONField()),
                ("snow_metadata", models.JSONField(blank=True, default=dict)),
                ("snow_created_at", models.DateTimeField(auto_now_add=True)),
                ("snow_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SnowAI Trading Weight",
                "verbose_name_plural": "SnowAI Trading Weights",
                "db_table": "snowai_trading_weights",
            },
        ),
    ]
