# Generated by Django 4.2.4 on 2025-12-11 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0068_snowaitradingweights"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIForwardTestingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text="Unique identifier for the trading model",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "cleaned_model_code",
                    models.TextField(
                        help_text="Cleaned Python code ready for forward testing"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when model was saved",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Timestamp of last update"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the model",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Forward Testing Model",
                "verbose_name_plural": "SnowAI Forward Testing Models",
                "ordering": ["-created_at"],
            },
        ),
    ]
