# Generated by Django 4.2.4 on 2025-12-11 08:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0069_snowaiforwardtestingmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveForwardTestModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Model name", max_length=255)),
                (
                    "asset",
                    models.CharField(help_text="Trading asset symbol", max_length=50),
                ),
                (
                    "interval",
                    models.CharField(
                        help_text="Trading interval (1d, 1h, etc)", max_length=10
                    ),
                ),
                ("model_code", models.TextField(help_text="Executable model code")),
                ("initial_equity", models.FloatField(default=10000.0)),
                ("current_equity", models.FloatField(default=10000.0)),
                ("num_positions", models.IntegerField(default=1)),
                ("take_profit", models.FloatField(help_text="Take profit value")),
                (
                    "take_profit_type",
                    models.CharField(help_text="PERCENTAGE or NUMBER", max_length=20),
                ),
                ("stop_loss", models.FloatField(help_text="Stop loss value")),
                (
                    "stop_loss_type",
                    models.CharField(help_text="PERCENTAGE or NUMBER", max_length=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                ("total_pnl", models.FloatField(default=0.0)),
                ("win_rate", models.FloatField(default=0.0)),
                (
                    "equity_curve",
                    models.TextField(
                        default="[]", help_text="JSON array of equity values"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(help_text="BUY or SELL", max_length=10),
                ),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("size", models.FloatField(help_text="Position size in units")),
                ("pnl", models.FloatField(default=0.0)),
                ("is_open", models.BooleanField(default=True)),
                ("take_profit_price", models.FloatField(blank=True, null=True)),
                ("stop_loss_price", models.FloatField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="snowAIWeb.activeforwardtestmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_time"],
            },
        ),
    ]
