# Generated by Django 4.2.4 on 2026-01-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0070_activeforwardtestmodel_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIPersonOfInterestUniqueV1",
            fields=[
                (
                    "person_id",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="people_of_interest/"
                    ),
                ),
                ("accomplishments", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("works", models.TextField(blank=True, null=True)),
                ("youtube_urls_json", models.TextField(blank=True, null=True)),
                (
                    "estimated_iq",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowai_people_of_interest_v1",
                "ordering": ["-created_at"],
            },
        ),
    ]
