# Generated by Django 4.2.4 on 2026-01-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0071_snowaipersonofinterestuniquev1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snowaipersonofinterestuniquev1",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
