# Generated by Django 4.2.4 on 2026-01-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0072_alter_snowaipersonofinterestuniquev1_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="snowaipersonofinterestuniquev1",
            name="field",
            field=models.CharField(
                choices=[
                    ("mathematics", "Mathematics"),
                    ("physics", "Physics"),
                    ("computer_science", "Computer Science"),
                    ("economics", "Economics"),
                    ("biology", "Biology"),
                    ("chemistry", "Chemistry"),
                    ("engineering", "Engineering"),
                    ("philosophy", "Philosophy"),
                    ("neuroscience", "Neuroscience"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
