# Generated by Django 4.2.4 on 2026-01-18 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0073_snowaipersonofinterestuniquev1_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIBacktestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("timeframe", models.CharField(db_index=True, max_length=10)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "initial_capital",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("take_profit", models.DecimalField(decimal_places=2, max_digits=8)),
                ("stop_loss", models.DecimalField(decimal_places=2, max_digits=8)),
                ("selected_functions", models.JSONField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("duration", models.CharField(max_length=100)),
                ("exposure_time", models.DecimalField(decimal_places=2, max_digits=8)),
                ("equity_final", models.DecimalField(decimal_places=2, max_digits=15)),
                ("equity_peak", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "return_percent",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "buy_hold_return",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("annual_return", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "volatility_annual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("sharpe_ratio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("sortino_ratio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("calmar_ratio", models.DecimalField(decimal_places=2, max_digits=8)),
                ("max_drawdown", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg_drawdown", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_drawdown_duration", models.CharField(max_length=100)),
                ("avg_drawdown_duration", models.CharField(max_length=100)),
                ("num_trades", models.IntegerField()),
                ("win_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("best_trade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("worst_trade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("avg_trade", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_trade_duration", models.CharField(max_length=100)),
                ("avg_trade_duration", models.CharField(max_length=100)),
                ("profit_factor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expectancy", models.DecimalField(decimal_places=2, max_digits=10)),
                ("plot_json", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIBacktestSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("config", models.JSONField()),
                ("status", models.CharField(default="initializing", max_length=100)),
                ("progress", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session",
                        to="snowAIWeb.snowaibacktestresult",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="snowaibacktestresult",
            index=models.Index(
                fields=["-created_at", "asset_symbol"],
                name="snowAIWeb_s_created_e9e593_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="snowaibacktestresult",
            index=models.Index(
                fields=["asset_symbol", "timeframe"],
                name="snowAIWeb_s_asset_s_8c3738_idx",
            ),
        ),
    ]
