# Generated by Django 4.2.4 on 2026-02-01 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0074_snowaibacktestresult_snowaibacktestsession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttrades",
            name="sector",
            field=models.CharField(
                blank=True, default="Unknown", max_length=100, null=True
            ),
        ),
        migrations.CreateModel(
            name="SnowAIAllEncompassingDailyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("asset", models.CharField(max_length=20)),
                ("sector", models.CharField(max_length=100)),
                ("r_squared", models.FloatField()),
                ("mss", models.FloatField()),
                ("current_trend", models.CharField(max_length=20)),
                ("current_price", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("has_open_position", models.BooleanField(default=False)),
                (
                    "position_type",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("take_profit_price", models.FloatField(blank=True, null=True)),
                ("stop_loss_price", models.FloatField(blank=True, null=True)),
                ("entry_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-r_squared"],
                "unique_together": {("date", "asset")},
            },
        ),
    ]
