# Generated by Django 4.2.4 on 2026-02-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0075_accounttrades_sector_snowaiallencompassingdailystock"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOfInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("asset_class", models.CharField(max_length=50)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("trading_date", models.DateField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "mss_assets_of_interest",
                "ordering": ["-trading_date", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["trading_date", "asset_class"],
                        name="mss_assets__trading_e2f879_idx",
                    ),
                    models.Index(
                        fields=["symbol"], name="mss_assets__symbol_6156f1_idx"
                    ),
                ],
                "unique_together": {("symbol", "trading_date")},
            },
        ),
    ]
