# Generated by Django 4.2.4 on 2026-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0076_assetofinterest"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIPaperTradingBacktestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("asset_symbol", models.CharField(max_length=50)),
                ("asset_name", models.CharField(max_length=200)),
                ("timeframe", models.CharField(max_length=10)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=20),
                ),
                (
                    "final_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "total_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "win_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "average_win",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "average_loss",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "largest_win",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "largest_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("trades_data", models.JSONField(default=list)),
                ("equity_curve", models.JSONField(default=list)),
                ("status", models.CharField(default="IN_PROGRESS", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "snowai_paper_trading_backtest_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowAITradingPerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("snapshot_date", models.DateTimeField(auto_now_add=True)),
                ("total_trades_all_time", models.IntegerField(default=0)),
                (
                    "total_profit_all_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_loss_all_time",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "overall_win_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("crypto_stats", models.JSONField(default=dict)),
                ("stocks_stats", models.JSONField(default=dict)),
                ("forex_stats", models.JSONField(default=dict)),
                ("indices_stats", models.JSONField(default=dict)),
                ("commodities_stats", models.JSONField(default=dict)),
                ("best_performing_asset", models.CharField(blank=True, max_length=50)),
                (
                    "best_performance_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("worst_performing_asset", models.CharField(blank=True, max_length=50)),
                (
                    "worst_performance_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("total_assets_traded", models.IntegerField(default=0)),
                ("active_positions", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "snowai_trading_performance_snapshot",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="SnowAITradeOrderExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=50)),
                ("asset_name", models.CharField(max_length=200)),
                ("asset_class", models.CharField(max_length=50)),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=8, default=1.0, max_digits=20),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("exit_reason", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "profit_loss_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("entry_timestamp", models.DateTimeField(db_index=True)),
                ("exit_timestamp", models.DateTimeField(blank=True, null=True)),
                ("entry_timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "exit_timezone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_paper_trade", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowai_trade_order_execution_record",
                "ordering": ["-entry_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["asset_symbol", "status"],
                        name="snowai_trad_asset_s_85761e_idx",
                    ),
                    models.Index(
                        fields=["entry_timestamp"],
                        name="snowai_trad_entry_t_8e0a10_idx",
                    ),
                    models.Index(
                        fields=["is_paper_trade"], name="snowai_trad_is_pape_961eba_idx"
                    ),
                ],
            },
        ),
    ]
