# Generated by Django 4.2.4 on 2026-02-12 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0077_snowaipapertradingbacktestsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAITradingModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "plain_english",
                    models.TextField(
                        help_text="The plain-English prompt the user typed"
                    ),
                ),
                (
                    "function_name",
                    models.CharField(
                        help_text="Python function name, e.g. is_high_volume",
                        max_length=100,
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        help_text="Raw Python source — must define function_name(df) -> bool"
                    ),
                ),
                ("asset_symbol", models.CharField(max_length=50)),
                ("asset_name", models.CharField(blank=True, max_length=200)),
                ("asset_class", models.CharField(blank=True, max_length=100)),
                ("timeframe", models.CharField(default="1H", max_length=10)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BUY", "Long / Buy"),
                            ("SELL", "Short / Sell"),
                            ("BOTH", "Both directions"),
                        ],
                        default="BUY",
                        max_length=4,
                    ),
                ),
                (
                    "take_profit_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.0,
                        help_text="Take-profit as % of entry price",
                        max_digits=6,
                    ),
                ),
                (
                    "stop_loss_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=4.0,
                        help_text="Stop-loss as % of entry price",
                        max_digits=6,
                    ),
                ),
                (
                    "position_size",
                    models.DecimalField(
                        decimal_places=2,
                        default=1000.0,
                        help_text="Dollar amount per position",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active - Running"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_signal", models.BooleanField(blank=True, null=True)),
                ("error_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SnowAI Trading Model",
                "verbose_name_plural": "SnowAI Trading Models",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="snowAIWeb_s_status_8bb5bb_idx"
                    ),
                    models.Index(
                        fields=["asset_symbol"], name="snowAIWeb_s_asset_s_42cb2d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SnowAIModelTrade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_symbol", models.CharField(max_length=50)),
                ("order_type", models.CharField(max_length=4)),
                ("entry_price", models.DecimalField(decimal_places=6, max_digits=20)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit_price",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(decimal_places=6, max_digits=20),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=6, default=1, max_digits=20),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=20, null=True
                    ),
                ),
                (
                    "profit_loss_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("TP_HIT", "Take Profit Hit"),
                            ("SL_HIT", "Stop Loss Hit"),
                            ("MANUAL", "Manually Closed"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("entry_timestamp", models.DateTimeField(auto_now_add=True)),
                ("exit_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="snowAIWeb.snowaitradingmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Model Trade",
                "verbose_name_plural": "SnowAI Model Trades",
                "ordering": ["-entry_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["outcome"], name="snowAIWeb_s_outcome_bca793_idx"
                    ),
                    models.Index(
                        fields=["asset_symbol"], name="snowAIWeb_s_asset_s_eeab19_idx"
                    ),
                    models.Index(
                        fields=["model", "outcome"],
                        name="snowAIWeb_s_model_i_e53f01_idx",
                    ),
                ],
            },
        ),
    ]
