# Generated by Django 4.2.4 on 2026-02-13 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0078_snowaitradingmodel_snowaimodeltrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacktestWatchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Ticker symbol used for charting (e.g. AAPL, BTC-USD, EURUSD=X)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable asset name (e.g. Apple Inc.)",
                        max_length=120,
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("Stocks", "Stocks"),
                            ("Crypto", "Crypto"),
                            ("Forex", "Forex"),
                            ("ETF", "ETF"),
                            ("Commodities", "Commodities"),
                            ("Indices", "Indices"),
                            ("Other", "Other"),
                        ],
                        default="Stocks",
                        max_length=20,
                    ),
                ),
                (
                    "yfinance_symbol",
                    models.CharField(
                        blank=True,
                        help_text="yFinance-specific symbol if different from display symbol",
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about why this asset is on the watchlist",
                        null=True,
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Backtest Watchlist Asset",
                "verbose_name_plural": "Backtest Watchlist Assets",
                "ordering": ["asset_class", "symbol"],
            },
        ),
    ]
