# Generated by Django 4.2.4 on 2026-03-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0079_backtestwatchlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIInstaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "SnowAI Insta Category",
                "verbose_name_plural": "SnowAI Insta Categories",
                "db_table": "snowai_insta_categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIInstaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("post_url", models.URLField(max_length=500)),
                (
                    "account_handle",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("POST", "Post"),
                            ("REEL", "Reel"),
                            ("TV", "IGTV"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                    ),
                ),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("shortcode", models.CharField(blank=True, max_length=50, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snowai_insta_posts",
                        to="snowAIWeb.snowaiinstacategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "SnowAI Insta Post",
                "verbose_name_plural": "SnowAI Insta Posts",
                "db_table": "snowai_insta_posts",
                "ordering": ["-date_added"],
            },
        ),
    ]
