# Generated by Django 4.2.4 on 2026-03-16 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0080_snowaiinstacategory_snowaiinstapost"),
    ]

    operations = [
        migrations.CreateModel(
            name="GAChromosome",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation", models.IntegerField(default=0)),
                ("functions", models.TextField()),
                ("fitness", models.FloatField(default=0.0)),
                ("win_rate", models.FloatField(default=0.0)),
                ("total_trades", models.IntegerField(default=0)),
                ("total_pnl", models.FloatField(default=0.0)),
                ("sharpe_ratio", models.FloatField(default=0.0)),
                ("max_drawdown", models.FloatField(default=0.0)),
                ("is_elite", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "market_snapshot",
                    models.TextField(
                        blank=True, help_text="Base64 PNG market-condition image"
                    ),
                ),
                (
                    "market_snapshot_meta",
                    models.TextField(
                        default="{}",
                        help_text="JSON metadata: avg_atr, trend_slope, vol_regime…",
                    ),
                ),
            ],
            options={
                "ordering": ["-fitness"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIGAModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "assets",
                    models.TextField(help_text="Comma-separated ticker symbols"),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                            ("1wk", "1 Week"),
                        ],
                        default="1d",
                        max_length=5,
                    ),
                ),
                ("start_year", models.IntegerField(default=2020)),
                ("end_year", models.IntegerField(default=2024)),
                ("initial_capital", models.FloatField(default=10000.0)),
                ("take_profit", models.FloatField(default=4.0, help_text="%")),
                ("stop_loss", models.FloatField(default=2.0, help_text="%")),
                ("population_size", models.IntegerField(default=30)),
                ("max_generations", models.IntegerField(default=20)),
                ("mutation_rate", models.FloatField(default=0.2)),
                (
                    "elite_fraction",
                    models.FloatField(
                        default=0.3, help_text="Top fraction kept unchanged"
                    ),
                ),
                ("rl_enabled", models.BooleanField(default=True)),
                ("rl_learning_rate", models.FloatField(default=0.01)),
                ("rl_q_table", models.TextField(blank=True, default="{}")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("current_generation", models.IntegerField(default=0)),
                ("progress", models.IntegerField(default=0, help_text="0-100 %")),
                ("error_message", models.TextField(blank=True)),
                ("allowed_functions", models.TextField(default="[]")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "SnowAI GA Model",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OHLCVCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                ("timeframe", models.CharField(max_length=5)),
                ("date", models.DateField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("volume", models.FloatField(default=0.0)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["asset", "timeframe", "date"],
                "indexes": [
                    models.Index(
                        fields=["asset", "timeframe"],
                        name="snowAIWeb_o_asset_ccf2b5_idx",
                    )
                ],
                "unique_together": {("asset", "timeframe", "date")},
            },
        ),
        migrations.CreateModel(
            name="GATradeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                ("entry_time", models.DateTimeField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("entry_price", models.FloatField()),
                ("exit_price", models.FloatField(blank=True, null=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("pnl", models.FloatField(default=0.0)),
                ("hit_tp", models.BooleanField(default=False)),
                ("hit_sl", models.BooleanField(default=False)),
                (
                    "chromosome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="snowAIWeb.gachromosome",
                    ),
                ),
            ],
            options={
                "ordering": ["entry_time"],
            },
        ),
        migrations.AddField(
            model_name="gachromosome",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chromosomes",
                to="snowAIWeb.snowaigamodel",
            ),
        ),
        migrations.CreateModel(
            name="GAGenerationSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("generation", models.IntegerField()),
                ("best_fitness", models.FloatField(default=0.0)),
                ("avg_fitness", models.FloatField(default=0.0)),
                ("worst_fitness", models.FloatField(default=0.0)),
                (
                    "diversity",
                    models.FloatField(
                        default=0.0, help_text="Fraction of unique combos in population"
                    ),
                ),
                ("top_combos", models.TextField(default="[]")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_summaries",
                        to="snowAIWeb.snowaigamodel",
                    ),
                ),
            ],
            options={
                "ordering": ["model", "generation"],
                "unique_together": {("model", "generation")},
            },
        ),
    ]
