# Generated by Django 4.2.4 on 2026-03-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0081_gachromosome_snowaigamodel_ohlcvcache_gatradelog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="snowaigamodel",
            name="logs",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
