# Generated by Django 4.2.4 on 2026-04-09 09:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0082_snowaigamodel_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIMomentCollage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collage_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "moment_uuids",
                    models.TextField(
                        help_text="Comma-separated moment UUIDs included in collage"
                    ),
                ),
                (
                    "collage_image_data",
                    models.TextField(help_text="Base64 encoded collage image"),
                ),
                (
                    "audio_data",
                    models.TextField(
                        blank=True,
                        help_text="Base64 encoded audio narration",
                        null=True,
                    ),
                ),
                ("total_moments", models.IntegerField(default=0)),
                ("event_name", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SnowAI Moment Collage",
                "verbose_name_plural": "SnowAI Moment Collages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowAIMomentEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "moment_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image_data",
                    models.TextField(
                        blank=True, help_text="Base64 encoded image", null=True
                    ),
                ),
                (
                    "video_data",
                    models.TextField(
                        blank=True, help_text="Base64 encoded video", null=True
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("mixed", "Mixed Media"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.TextField(
                        blank=True, help_text="Comma-separated tags", null=True
                    ),
                ),
                ("event_name", models.CharField(blank=True, max_length=200, null=True)),
                ("location", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "moment_date",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_size_kb",
                    models.IntegerField(
                        default=0, help_text="Approximate file size in KB"
                    ),
                ),
                ("is_favorite", models.BooleanField(db_index=True, default=False)),
            ],
            options={
                "verbose_name": "SnowAI Moment",
                "verbose_name_plural": "SnowAI Moments",
                "ordering": ["-moment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-moment_date", "-created_at"],
                        name="snowAIWeb_s_moment__2c967c_idx",
                    ),
                    models.Index(
                        fields=["is_favorite"], name="snowAIWeb_s_is_favo_7bded6_idx"
                    ),
                ],
            },
        ),
    ]
