# Generated by Django 4.2.4 on 2026-04-09 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0083_snowaimomentcollage_snowaimomententry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAIMomentSlideshow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slideshow_uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "moment_uuids",
                    models.TextField(
                        help_text="Comma-separated moment UUIDs included in slideshow"
                    ),
                ),
                ("audio_data", models.TextField(help_text="Base64 encoded audio file")),
                (
                    "audio_duration_seconds",
                    models.FloatField(
                        default=0, help_text="Duration of audio in seconds"
                    ),
                ),
                ("total_moments", models.IntegerField(default=0)),
                ("event_name", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SnowAI Moment Slideshow",
                "verbose_name_plural": "SnowAI Moment Slideshows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="SnowAIMomentCollage",
        ),
    ]
