# Generated by Django 4.2.4 on 2026-04-16 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0084_snowaimomentslideshow_delete_snowaimomentcollage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAISpotifyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "snowai_spotify_categories",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="SnowAISpotifyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotify_type",
                    models.CharField(
                        choices=[
                            ("track", "Track"),
                            ("album", "Album"),
                            ("playlist", "Playlist"),
                            ("artist", "Artist"),
                            ("episode", "Episode"),
                            ("show", "Podcast / Show"),
                        ],
                        default="track",
                        max_length=20,
                    ),
                ),
                ("spotify_id", models.CharField(max_length=100)),
                ("spotify_url", models.URLField(blank=True, max_length=500, null=True)),
                ("title", models.CharField(max_length=300)),
                ("artist", models.CharField(blank=True, max_length=300, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spotify_entries",
                        to="snowAIWeb.snowaispotifycategory",
                    ),
                ),
            ],
            options={
                "db_table": "snowai_spotify_entries",
                "ordering": ["-date_added"],
                "unique_together": {("spotify_type", "spotify_id")},
            },
        ),
    ]
