# Generated by Django 4.2.4 on 2026-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0085_snowaispotifycategory_snowaispotifyentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="MSSHistoricalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=32)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("forex", "Forex"),
                            ("stocks", "Stocks"),
                            ("indices", "Indices"),
                            ("commodities", "Commodities"),
                            ("bonds", "Bonds"),
                        ],
                        default="stocks",
                        max_length=20,
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=64, null=True)),
                ("date_taken", models.DateField(db_index=True)),
                ("period_days", models.IntegerField(db_index=True)),
                ("mss", models.FloatField()),
                ("r_squared", models.FloatField()),
                ("volatility", models.FloatField()),
                ("normalized_volatility", models.FloatField()),
                ("trend_consistency", models.FloatField()),
                ("trend_strength", models.FloatField()),
                ("liquidity_factor", models.FloatField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stable", "Stable"),
                            ("choppy", "Choppy"),
                            ("volatile", "Volatile"),
                        ],
                        max_length=10,
                    ),
                ),
                ("current_price", models.FloatField()),
                ("price_change", models.FloatField()),
                ("avg_volume", models.BigIntegerField()),
                ("data_points", models.IntegerField()),
                ("analyst_rating_pct", models.FloatField(blank=True, null=True)),
                (
                    "analyst_bias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("put_call_ratio", models.FloatField(blank=True, null=True)),
                (
                    "put_call_bias",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_taken", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "period_days", "date_taken"],
                        name="snowAIWeb_m_symbol_5afa9c_idx",
                    ),
                    models.Index(
                        fields=["date_taken", "period_days"],
                        name="snowAIWeb_m_date_ta_6c8353_idx",
                    ),
                ],
                "unique_together": {("symbol", "date_taken", "period_days")},
            },
        ),
    ]
