# Generated by Django 4.2.4 on 2026-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0086_msshistoricalrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradePosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(max_length=20)),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")],
                        default="long",
                        max_length=10,
                    ),
                ),
                ("entry_price", models.FloatField()),
                (
                    "sl_dollars",
                    models.FloatField(help_text="Dollar amount you lose if SL hits"),
                ),
                (
                    "tp_dollars",
                    models.FloatField(help_text="Dollar amount you gain if TP hits"),
                ),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
