# Generated by Django 4.2.4 on 2026-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0087_tradeposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="tradeposition",
            name="sl_price",
            field=models.FloatField(help_text="Actual SL price level", null=True),
        ),
        migrations.AddField(
            model_name="tradeposition",
            name="tp_price",
            field=models.FloatField(help_text="Actual TP price level", null=True),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="sl_dollars",
            field=models.FloatField(help_text="Dollar loss if SL is hit", null=True),
        ),
        migrations.AlterField(
            model_name="tradeposition",
            name="tp_dollars",
            field=models.FloatField(help_text="Dollar gain if TP is hit", null=True),
        ),
    ]
