# Generated by Django 4.2.4 on 2026-05-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0089_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAICompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("sector", models.CharField(blank=True, default="", max_length=100)),
                (
                    "logo_base64",
                    models.TextField(
                        blank=True, default="", help_text="Base64-encoded logo image"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SnowAICompanyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "Web Link"),
                            ("pdf", "PDF Document"),
                            ("youtube", "YouTube Video"),
                        ],
                        default="url",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="snowAIWeb.snowaicompany",
                    ),
                ),
            ],
            options={
                "ordering": ["link_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="SnowAICompanyKeyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "photo_base64",
                    models.TextField(
                        blank=True, default="", help_text="Base64-encoded profile photo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_people",
                        to="snowAIWeb.snowaicompany",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
