# Generated by Django 4.2.4 on 2026-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0090_snowaicompany_snowaicompanylink_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snowaihedgefundentity",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="snowaihedgefundkeyperson",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="snowaihedgefundentity",
            name="logo_base64",
            field=models.TextField(
                blank=True, help_text="Base64 encoded logo image", null=True
            ),
        ),
        migrations.AddField(
            model_name="snowaihedgefundkeyperson",
            name="photo_base64",
            field=models.TextField(
                blank=True, help_text="Base64 encoded photo", null=True
            ),
        ),
    ]
