# Generated by Django 4.2.4 on 2026-06-08 20:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0091_remove_snowaihedgefundentity_logo_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowAICompanyTranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript_uuid",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Stable client-side UUID used for upsert operations.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "company_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="FK → your company table PK (snowai_companies_of_interest.id).",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Denormalised company name — avoids a JOIN in the viewer.",
                        max_length=300,
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Title of the video, meeting, or document being transcribed.",
                        max_length=500,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL of the source (YouTube, meeting link, article, etc.).",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "youtube_video_id",
                    models.CharField(
                        blank=True,
                        help_text="Extracted YouTube video ID — null for non-YT sources.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="youtube",
                        help_text="youtube | meeting | earnings_call | conference | interview | other",
                        max_length=30,
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "speaker_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. CEO, CFO, Analyst",
                        max_length=300,
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Q3 2024 Earnings Call, Davos 2024 Panel",
                        max_length=300,
                    ),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                (
                    "full_transcript_text",
                    models.TextField(help_text="The full captured transcript text."),
                ),
                (
                    "transcript_language",
                    models.CharField(
                        default="en-US",
                        help_text="BCP-47 language tag, e.g. en-US, fr-FR, zh-CN.",
                        max_length=20,
                    ),
                ),
                (
                    "recording_duration_seconds",
                    models.IntegerField(
                        blank=True,
                        help_text="Wall-clock seconds of the live recording session.",
                        null=True,
                    ),
                ),
                ("word_count", models.IntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raw", "Raw — not yet reviewed"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed — analysis done"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="raw",
                        max_length=20,
                    ),
                ),
                (
                    "transcription_method",
                    models.CharField(
                        default="browser_speech_api",
                        help_text="browser_speech_api | manual | ai_generated | imported",
                        max_length=50,
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human or AI-generated summary.",
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["Point 1", "Point 2", ...]',
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='["monetary_policy", "inflation", ...]',
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="-1.0 (very negative) → +1.0 (very positive)",
                        null=True,
                    ),
                ),
                (
                    "analyst_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form notes added after review.",
                    ),
                ),
                ("custom_tags", models.JSONField(blank=True, default=list)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the live recording was made.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "snowai_company_transcripts",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "status"],
                        name="snowai_comp_company_e95f71_idx",
                    ),
                    models.Index(
                        fields=["company_id", "recorded_at"],
                        name="snowai_comp_company_068bdc_idx",
                    ),
                    models.Index(
                        fields=["source_type"], name="snowai_comp_source__375bc9_idx"
                    ),
                    models.Index(
                        fields=["transcript_language"],
                        name="snowai_comp_transcr_d8f688_idx",
                    ),
                    models.Index(
                        fields=["status"], name="snowai_comp_status_40a2ea_idx"
                    ),
                    models.Index(
                        fields=["recorded_at"], name="snowai_comp_recorde_962105_idx"
                    ),
                ],
            },
        ),
    ]
