# Generated by Django 4.2.4 on 2026-06-10 11:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0092_snowaicompanytranscript"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowCOICompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("sector", models.CharField(blank=True, default="", max_length=100)),
                (
                    "logo_base64",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Base64 data-URI of the company logo.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowcoi_companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SnowCOICompanyLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("url", "Web Link"),
                            ("pdf", "PDF Document"),
                            ("youtube", "YouTube Video"),
                        ],
                        default="url",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ai_summary", models.TextField(blank=True, default="")),
                (
                    "ai_key_points",
                    models.JSONField(
                        blank=True, default=list, help_text='["Point 1", ...]'
                    ),
                ),
                (
                    "ai_topics",
                    models.JSONField(
                        blank=True, default=list, help_text='["topic_one", ...]'
                    ),
                ),
                (
                    "ai_sentiment_score",
                    models.FloatField(blank=True, help_text="-1.0 to +1.0", null=True),
                ),
                ("ai_analyst_notes", models.TextField(blank=True, default="")),
                ("ai_analysed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "snowcoi_company_links",
                "ordering": ["link_type", "title"],
            },
        ),
        migrations.CreateModel(
            name="SnowCOIKeyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, default="", max_length=255)),
                ("bio", models.TextField(blank=True, default="")),
                (
                    "photo_base64",
                    models.TextField(
                        blank=True, default="", help_text="Base64 data-URI."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "snowcoi_key_people",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SnowCOITranscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript_uuid",
                    models.CharField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Stable client-generated UUID used for upsert operations.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "company_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="FK -> SnowCOICompany.id (plain int for portability).",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Denormalised name to avoid JOINs.",
                        max_length=300,
                    ),
                ),
                (
                    "source_title",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("source_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="youtube",
                        help_text="youtube | meeting | earnings_call | conference | interview | other",
                        max_length=30,
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "speaker_role",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "event_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("event_date", models.DateField(blank=True, null=True)),
                ("full_transcript_text", models.TextField()),
                (
                    "transcript_language",
                    models.CharField(default="en-US", max_length=20),
                ),
                (
                    "recording_duration_seconds",
                    models.IntegerField(blank=True, null=True),
                ),
                ("word_count", models.IntegerField(default=0, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raw", "Raw - not yet reviewed"),
                            ("reviewed", "Reviewed"),
                            ("processed", "Processed - AI analysis done"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="raw",
                        max_length=20,
                    ),
                ),
                (
                    "transcription_method",
                    models.CharField(
                        default="browser_speech_api",
                        help_text="browser_speech_api | manual | ai_generated | imported",
                        max_length=50,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("sentiment_score", models.FloatField(blank=True, null=True)),
                ("analyst_notes", models.TextField(blank=True, default="")),
                ("custom_tags", models.JSONField(blank=True, default=list)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "snowcoi_transcripts",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="SnowVTRRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transcript_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                (
                    "youtube_video_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "primary_speaker_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "speaker_organization",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "speaker_country_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "speaker_country_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("full_transcript_text", models.TextField()),
                ("video_duration_seconds", models.IntegerField(blank=True, null=True)),
                ("transcript_language", models.CharField(default="en", max_length=20)),
                ("video_upload_date", models.DateTimeField(blank=True, null=True)),
                (
                    "transcription_method",
                    models.CharField(default="browser_speech_api", max_length=50),
                ),
                (
                    "transcript_confidence_score",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "processing_status",
                    models.CharField(db_index=True, default="completed", max_length=30),
                ),
                (
                    "content_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("economic_topics", models.JSONField(blank=True, default=list)),
                ("custom_tags", models.JSONField(blank=True, default=list)),
                ("word_count", models.IntegerField(default=0, editable=False)),
                ("sentiment_analysis_score", models.FloatField(blank=True, null=True)),
                ("key_phrases_extracted", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "snowvtr_records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="snowaicompanykeyperson",
            name="company",
        ),
        migrations.RemoveField(
            model_name="snowaicompanylink",
            name="company",
        ),
        migrations.DeleteModel(
            name="SnowAICompanyTranscript",
        ),
        migrations.DeleteModel(
            name="SnowAICompany",
        ),
        migrations.DeleteModel(
            name="SnowAICompanyKeyPerson",
        ),
        migrations.DeleteModel(
            name="SnowAICompanyLink",
        ),
        migrations.AddIndex(
            model_name="snowvtrrecord",
            index=models.Index(
                fields=["youtube_video_id"], name="snowvtr_rec_youtube_fae921_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowvtrrecord",
            index=models.Index(
                fields=["processing_status"], name="snowvtr_rec_process_fe5256_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowvtrrecord",
            index=models.Index(
                fields=["transcript_language"], name="snowvtr_rec_transcr_baed0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowvtrrecord",
            index=models.Index(
                fields=["created_at"], name="snowvtr_rec_created_ca15bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(
                fields=["company_id", "status"], name="snowcoi_tra_company_34623f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(
                fields=["company_id", "recorded_at"],
                name="snowcoi_tra_company_4e2ceb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(
                fields=["source_type"], name="snowcoi_tra_source__1c0786_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(
                fields=["transcript_language"], name="snowcoi_tra_transcr_db1771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(fields=["status"], name="snowcoi_tra_status_10d875_idx"),
        ),
        migrations.AddIndex(
            model_name="snowcoitranscript",
            index=models.Index(
                fields=["recorded_at"], name="snowcoi_tra_recorde_8e3196_idx"
            ),
        ),
        migrations.AddField(
            model_name="snowcoikeyperson",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_people",
                to="snowAIWeb.snowcoicompany",
            ),
        ),
        migrations.AddField(
            model_name="snowcoicompanylink",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="snowAIWeb.snowcoicompany",
            ),
        ),
    ]
