# Generated by Django 4.2.4 on 2026-06-12 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "snowAIWeb",
            "0093_snowcoicompany_snowcoicompanylink_snowcoikeyperson_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="SnowVTRRecord",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_company_e95f71_idx",
            old_name="snowcoi_tra_company_34623f_idx",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_company_068bdc_idx",
            old_name="snowcoi_tra_company_4e2ceb_idx",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_source__375bc9_idx",
            old_name="snowcoi_tra_source__1c0786_idx",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_transcr_d8f688_idx",
            old_name="snowcoi_tra_transcr_db1771_idx",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_status_40a2ea_idx",
            old_name="snowcoi_tra_status_10d875_idx",
        ),
        migrations.RenameIndex(
            model_name="snowcoitranscript",
            new_name="snowai_comp_recorde_962105_idx",
            old_name="snowcoi_tra_recorde_8e3196_idx",
        ),
        migrations.AlterModelTable(
            name="snowcoicompany",
            table="snowaiweb_snowaicompany",
        ),
        migrations.AlterModelTable(
            name="snowcoicompanylink",
            table="snowaiweb_snowaicompanylink",
        ),
        migrations.AlterModelTable(
            name="snowcoikeyperson",
            table="snowaiweb_snowaicompanykeyperson",
        ),
        migrations.AlterModelTable(
            name="snowcoitranscript",
            table="snowai_company_transcripts",
        ),
    ]
