# Generated by Django 4.2.4 on 2026-06-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0094_delete_snowvtrrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultWatchlistAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30, unique=True)),
                ("label", models.CharField(blank=True, max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("stocks", "Stocks"),
                            ("forex", "Forex"),
                            ("crypto", "Crypto"),
                            ("indices", "Indices"),
                            ("commodities", "Commodities"),
                            ("bonds", "Bonds"),
                            ("etf", "ETF"),
                            ("other", "Other"),
                        ],
                        default="stocks",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "snowvault_watchlist_asset",
                "ordering": ["category", "symbol"],
            },
        ),
    ]
