# Generated by Django 4.2.4 on 2026-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0095_snowvaultwatchlistasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultScannerCache",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("results_json", models.TextField(default="[]")),
                ("count", models.IntegerField(default=0)),
                ("total_scanned", models.IntegerField(default=0)),
                ("min_market_cap", models.BigIntegerField(default=10000000000)),
                ("scanned_at", models.CharField(blank=True, max_length=32, null=True)),
                ("is_running", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_scanner_cache",
            },
        ),
        migrations.CreateModel(
            name="SnowVaultTickerMeta",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sector", models.CharField(blank=True, default="", max_length=128)),
                ("curr_price", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_ticker_meta",
            },
        ),
    ]
