# Generated by Django 4.2.4 on 2026-07-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0096_snowvaultscannercache_snowvaulttickermeta"),
    ]

    operations = [
        migrations.AddField(
            model_name="snowvaultscannercache",
            name="last_triggered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
