# Generated by Django 4.2.4 on 2026-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0097_snowvaultscannercache_last_triggered_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultScannerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                ("snapshot_date", models.DateField(db_index=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("sector", models.CharField(blank=True, default="", max_length=128)),
                ("score", models.FloatField(blank=True, null=True)),
                ("signal", models.CharField(blank=True, default="", max_length=64)),
                ("direction", models.CharField(blank=True, default="", max_length=16)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("ai_verdict", models.CharField(blank=True, default="", max_length=32)),
                ("ai_opportunity_score", models.IntegerField(blank=True, null=True)),
                ("raw_scanner_json", models.TextField(default="{}")),
                ("ai_analysis_json", models.TextField(blank=True, null=True)),
                ("saved_count", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_scanner_history",
                "indexes": [
                    models.Index(
                        fields=["snapshot_date"], name="snowvault_s_snapsho_d6a318_idx"
                    ),
                    models.Index(
                        fields=["ticker"], name="snowvault_s_ticker_b8f1aa_idx"
                    ),
                ],
                "unique_together": {("ticker", "snapshot_date")},
            },
        ),
    ]
