# Generated by Django 4.2.4 on 2026-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0098_snowvaultscannerhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="snowvaultscannerhistory",
            name="ai_runs_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="snowvaultscannerhistory",
            name="ai_synthesis_json",
            field=models.TextField(blank=True, null=True),
        ),
    ]
