# Generated by Django 4.2.4 on 2026-07-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0099_snowvaultscannerhistory_ai_runs_json_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowGlobalStockPick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("flag", models.CharField(default="🌍", max_length=20)),
                ("sector", models.CharField(max_length=100)),
                ("rec", models.CharField(max_length=30)),
                ("conviction", models.IntegerField(blank=True, null=True)),
                ("thesis", models.TextField(blank=True, default="")),
                ("risk", models.TextField(blank=True, default="")),
                ("catalysts", models.JSONField(blank=True, default=list)),
                (
                    "analyst_target",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "sub_sector",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "price_at_save",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("market_cap", models.CharField(blank=True, default="", max_length=50)),
                ("market_outlook", models.TextField(blank=True, default="")),
                ("top_pick", models.BooleanField(default=False)),
                ("top_pick_reason", models.TextField(blank=True, default="")),
                ("source_list", models.JSONField(blank=True, default=list)),
                ("article_count", models.IntegerField(blank=True, null=True)),
                ("tf_context", models.CharField(blank=True, default="", max_length=20)),
                ("date_saved", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "snow_global_stock_picks",
                "ordering": ["-created_at"],
                "unique_together": {("symbol", "country", "sector", "date_saved")},
            },
        ),
    ]
