# Generated by Django 4.2.4 on 2026-09-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0100_snowglobalstockpick"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultGlobalPicksScanCache",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("results_json", models.TextField(default="{}")),
                ("total_tickers", models.IntegerField(default=0)),
                ("total_countries", models.IntegerField(default=0)),
                ("scanned_at", models.CharField(blank=True, max_length=32, null=True)),
                ("is_running", models.BooleanField(default=False)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_global_picks_scan_cache",
            },
        ),
    ]
