# Generated by Django 4.2.4 on 2026-09-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0101_snowvaultglobalpicksscancache"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultTickerStabilityCache",
            fields=[
                (
                    "ticker",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("combined_win_rate", models.FloatField(blank=True, null=True)),
                ("stability_score", models.FloatField(blank=True, null=True)),
                ("occurrence_count", models.IntegerField(default=0)),
                ("resolved_count", models.IntegerField(default=0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_ticker_stability_cache",
            },
        ),
        migrations.CreateModel(
            name="SnowVaultTrendScannerGateLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16)),
                (
                    "market_regime",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "ai_returns_required",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("min_stability", models.FloatField(blank=True, null=True)),
                ("max_age_days", models.IntegerField(blank=True, null=True)),
                ("result", models.BooleanField()),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("snapshot_date_used", models.DateField(blank=True, null=True)),
                (
                    "direction_found",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "ai_verdict_found",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("stability_score_found", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "snowvault_trend_scanner_gate_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["ticker", "-created_at"],
                        name="snowvault_t_ticker_e11587_idx",
                    )
                ],
            },
        ),
    ]
