# Generated by Django 4.2.4 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snowAIWeb", "0102_snowvaulttickerstabilitycache_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnowVaultPaperPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset", models.CharField(db_index=True, max_length=30)),
                (
                    "direction",
                    models.CharField(
                        choices=[("long", "Long"), ("short", "Short")], max_length=10
                    ),
                ),
                ("quantity", models.FloatField()),
                ("entry_price", models.FloatField()),
                ("tp_price", models.FloatField(blank=True, null=True)),
                ("tp_percent", models.FloatField(blank=True, null=True)),
                ("tp_dollars", models.FloatField(blank=True, null=True)),
                ("sl_price", models.FloatField(blank=True, null=True)),
                ("sl_percent", models.FloatField(blank=True, null=True)),
                ("sl_dollars", models.FloatField(blank=True, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED_TP", "Closed — Take Profit"),
                            ("CLOSED_SL", "Closed — Stop Loss"),
                            ("CLOSED_MANUAL", "Closed — Manual"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("closed_price", models.FloatField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("realized_pnl_dollars", models.FloatField(blank=True, null=True)),
                ("realized_pnl_percent", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(blank=True, default="manual", max_length=30),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "snowvault_paper_positions",
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["asset", "status"], name="snowvault_p_asset_4ee83c_idx"
                    )
                ],
            },
        ),
    ]
